### ISSUE TITLE
Fatal error: Class 'PHPlot\PHPlot\PHPLot_truecolor' on a fresh new install from composer

### ISSUE THREAD

**Issue by remluben** [AJRepo/PHPlot#9]
Hello,

first of all I want to thank you for the good work and trying to move the old package to composer + packagist.

Unfortunately moving to composer did not work for me.

Steps to reproduce:

```
# not sure if this is correct, but I could not find AJRepo/PHPlot in packagist, just your https://github.com/PHPlot/phplot package
composer require phplot/phplot 
# just to make sure I also did
composer dump-autoload
```

Within the PHP application the class could not be found:

> Fatal error: Uncaught Error: Class 'PHPlot\PHPlot\PHPlot_truecolor' not found

In my opinion, there's probably an error with your namespacing and classnames.

* `PHPlot_truecolor` as a class name differs from `phplot_truecolor.php` as a filename
* as well as `PHPlot` as a class name differs from `phplot.php` as a filename

What do you think? Do you accept PRs? If so, should the work be continued on this repository or on https://github.com/PHPlot/phplot ? What's the idea behind?

Kind regards,
Benjamin

**Comment by remluben** [comment]
Additional notes on this issue: It seems as if there's a mismatch between the namespace definition inside the libraries class files `PHPlot\PHPlot` and the namespace defined in *composer.json* that is defined as `phplot\phplot`.

The issue is probably something that does not effect the library when used in a Windows environment (assumption, I did not test it myself)

**Comment by AJRepo** [comment]
Thanks for the report!

>  Do you accept PRs? If so, should the work be continued on this repository or on https://github.com/PHPlot/phplot ? What's the idea behind?

- Yes, glad to accept PRs. 
- I moved from https://github.com/AJRepo/phplot to https://github.com/PHPlot/phplot in order to set it up as a github "organization" which should allow more flexibility in collaboration.
- Which to work in does not matter to me. I'd just like to try to keep clean git merges and keep development branches separate until they are ready for merging into a released version. 

> not sure if this is correct, but I could not find AJRepo/PHPlot in packagist

Yes - when I released it on packagist I pointed it to PHPlot/PHPlot . The two code bases are in sync, but I didn't want to delete AJRepo for those who already linked to it.  


> It seems as if there's a mismatch between the namespace definition inside the libraries class files PHPlot\PHPlot and the namespace defined in composer.json that is defined as phplot\phplot. The issue is probably something that does not effect the library when used in a Windows environment (assumption, I did not test it myself)

I don't have a windows environment, but couldn't replicate your issue on my environment (Linux).  Reading about this issue - some suggest that this kind of error might be related to the  autoload process?

**Comment by remluben** [comment]
Hey, thanks for your response.

I have to disagree with your feedback about probable other issues, but I am not a hundred percent sure.

When I have a look at the PSR-4 docs at https://www.php-fig.org/psr/psr-4/ it says:

> The terminating class name corresponds to a file name ending in .php. The file name MUST match the case of the terminating class name.

I made a quick check and managed to run the application when adjusting namespace and classnames accordingly.

I am going to open a pull request soon. I am looking forward to your feedback then.

**Comment by AJRepo** [comment]
Closing with tag 8.0.0.1
